# test-process/.github/workflows/trigger-custom-action.yml
name: Trigger Custom Action in Repo 2

on:
  push:
    branches:
      - main

jobs:
  call-custom-action-in-repo2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Call custom action in Repo 2
        uses: repo2-owner/repo2-name/path-to-action@main
        with:
          some-input: "value"
