name: "Test GitHub Tools Composite Action"

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  test_composite_action:
    runs-on: ubuntu-latest  # Specifies the operating system

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Check out the code of the current repository

      - name: Call External Action from wg-tools
        uses: wg-test/wg-tools/.github/actions@main
        with:
          # If the external action requires inputs, pass them here
          input1: "value1"
          input2: "value2"
